name: Build and Publish Teams Desktop Package

on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      FIFTYONE_TEAMS_PYPI_PASSWORD:
        required: true
      GAR_PYTHON_REPO:
        required: true
      GOOGLE_SERVICE_ACCOUNT:
        required: true
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build-and-publish-desktop:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform:
          - mac-arm64
          - mac-x86_64
          - linux-x86_64
          - linux-aarch64
          - win-amd64
    steps:
      - name: Clone fiftyone-teams
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - id: auth
        name: Authenticate to Google Cloud
        if: inputs.publish == 'internal'
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          pip install --upgrade pip setuptools wheel twine

      - name: Install package
        working-directory: package/desktop
        run: pip install --no-deps -e .

      - name: Fetch app dependency cache
        uses: actions/cache@v2
        with:
          path: app/node_modules
          key: npm-${{ hashFiles('app/packages/desktop/package.json') }}
          restore-keys: |
            npm-${{ hashFiles('app/packages/desktop/package.json') }}
            npm-

      - name: Install app dependencies
        working-directory: app/packages/desktop
        run: yarn

      - name: Package App (Non-Windows)
        if: matrix.platform != 'win-amd64'
        working-directory: app/packages/desktop
        run: yarn package-${{ matrix.platform }} --publish never

      - name: Package App (Windows)
        if:  matrix.platform == 'win-amd64'
        working-directory: app/
        run: |
          docker run --rm \
           --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
           --env ELECTRON_CACHE="/root/.cache/electron" \
           --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
           -v ${PWD}:/project \
           -v ~/.cache/electron:/root/.cache/electron \
           -v ~/.cache/electron-builder:/root/.cache/electron-builder \
           electronuserland/builder:wine \
           yarn workspace FiftyOne package-${{ matrix.platform }} --publish never

      - name: Build wheel
        working-directory: package/desktop
        run: python setup.py bdist_wheel --plat-name ${{ matrix.platform }}

      - name: Publish desktop to Google Artifact Registry
        if: inputs.publish == 'internal'
        working-directory: package/desktop
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_PASSWORD: ${{ steps.auth.outputs.access_token }}
          TWINE_REPOSITORY_URL: https://${{ secrets.GAR_PYTHON_REPO }}
          TWINE_USERNAME: oauth2accesstoken
        run: twine upload dist/*

      - name: Publish teams app to pypi.fiftyone.ai
        if: inputs.publish == 'external'
        working-directory: package/teams
        env:
          TWINE_NON_INTERACTIVE: 1
          TWINE_PASSWORD: ${{ secrets.FIFTYONE_TEAMS_PYPI_PASSWORD }}
          TWINE_REPOSITORY_URL: https://pypi.fiftyone.ai
          TWINE_USERNAME: teams-ci
        run: twine upload dist/*
