name: Build DB

on: push

jobs:
  build-db:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
        # with:
        #   submodules: true
      - name: Build wheel (Linux)
        run: |
          cd package/db
          python3 setup.py bdist_wheel --plat-name linux
      - name: Build wheel (macOS)
        run: |
          cd package/db
          python3 setup.py bdist_wheel --plat-name mac
      - name: Upload wheel (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-linux
          path: package/db/dist/*linux*.whl
      - name: Upload wheel (macOS)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-macos
          path: package/db/dist/*macos*.whl
