name: Builds and publishes the fiftyone-db package

on:
  push:
    tags:
      - db-v*
  pull_request:
    paths:
      - package/db/**
      - .github/workflows/build-db.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Set environment
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          if [[ $RELEASE_TAG =~ ^refs\/tags\/db-v.*-rc\..*$ ]]; then
             echo "RELEASE_VERSION=$(echo "${{ github.ref }}" | sed "s/^refs\/tags\/db-v//")" >> $GITHUB_ENV
          fi
      - name: Build sdist
        run: |
          cd package/db
          python setup.py sdist
      - name: Upload wheel(s)
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: package/db/dist/*.tar.gz

  test:
    runs-on: ubuntu-20.04
    needs: build
    env:
      FIFTYONE_DO_NOT_TRACK: true
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
      - name: Download fiftyone-db wheel
        uses: actions/download-artifact@v2
        with:
          name: sdist
          path: downloads
      - name: Install fiftyone-db
        run: |
          pip3 install downloads/fiftyone_db-*.tar.gz
      - name: Install test dependencies
        run: |
          pip3 install pytest
      - name: Run tests
        run: |
          cd package/db/
          python3 -m pytest --verbose tests/

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/db-v')
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: sdist
          path: downloads
      - name: Install dependencies
        run: |
          pip install twine
      - name: Set environment
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_PYPI_TOKEN }}" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY=pypi" >> $GITHUB_ENV
      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_NON_INTERACTIVE: 1
        run: |
          python -m twine upload downloads/*.tar.gz
