name: Build and Release Dev Images

on:
  push:
    branches:
      - develop
    tags-ignore:
      - bump-*
      - candidate
      - release
    paths:
      - .github/workflows/**
      - app/**
      - deployment/docker/**
      - fiftyone/**
      - package/desktop/**
      - package/teams/**
      - setup.py

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  get-versions-and-changes:
    uses: ./.github/workflows/versions-and-changes.yml
    with:
      commit-string-search: 'automated dev version bump'

  bump-versions:
    needs: get-versions-and-changes
    uses: ./.github/workflows/bump-package-versions.yml
    with:
      bump-type: dev
      commit-prefix: 'automated dev version bump'
      fiftyone-changed: ${{ needs.get-versions-and-changes.outputs.fiftyone-changed }}
      teams-app-changed: ${{ needs.get-versions-and-changes.outputs.teams-app-changed }}
      teams-desktop-changed: ${{ needs.get-versions-and-changes.outputs.teams-desktop-changed }}
      old-fiftyone-version: ${{ needs.get-versions-and-changes.outputs.fiftyone-version }}
      old-teams-app-version: ${{ needs.get-versions-and-changes.outputs.teams-app-version }}
      old-teams-desktop-version: ${{ needs.get-versions-and-changes.outputs.teams-desktop-version }}
    secrets: inherit

  publish-fiftyone-teams-package:
    needs: [bump-versions, get-versions-and-changes]
    if: needs.get-versions-and-changes.outputs.fiftyone-changed == 'true'
    uses: ./.github/workflows/build-fiftyone-package.yml
    with:
      ref: teams-v${{ needs.bump-versions.outputs.fiftyone-version }}
      publish: internal
    secrets: inherit

  publish-teams-app-package:
    needs: [bump-versions, get-versions-and-changes]
    if: needs.get-versions-and-changes.outputs.teams-app-changed == 'true'
    uses: ./.github/workflows/build-teams-app-package.yml
    with:
      ref: teams-app-v${{ needs.bump-versions.outputs.teams-app-version }}
      publish: internal
    secrets: inherit

  publish-teams-desktop-package:
    needs: [bump-versions, get-versions-and-changes]
    if: needs.get-versions-and-changes.outputs.teams-desktop-changed == 'true'
    uses: ./.github/workflows/build-teams-desktop-package.yml
    with:
      ref: teams-desktop-v${{ needs.bump-versions.outputs.teams-desktop-version }}
      publish: internal
    secrets: inherit

  publish-teams-app-image:
    needs: [bump-versions, get-versions-and-changes, publish-teams-app-package, publish-fiftyone-teams-package ]
    if: always() && contains((${{ needs.publish-teams-app-package.result }} ${{ needs.publish-fiftyone-teams-package.result }}), 'success')
    uses: ./.github/workflows/build-publish-container.yml
    with:
      fiftyone-version: ${{ needs.bump-versions.outputs.fiftyone-version }}
      publish: internal
      teams-app-version: ${{ needs.bump-versions.outputs.teams-app-version }}
    secrets: inherit

  deploy-dev-environment:
    needs: [bump-versions, publish-teams-app-image]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      domain-name: voxel51.dev.fiftyone.ai
      environment: dev
      fiftyone-version: ${{ needs.bump-versions.outputs.fiftyone-version }}
      teams-app-version: ${{ needs.bump-versions.outputs.teams-app-version }}
    secrets: inherit
