name: Build DB

on:
  push:
    branches:
      # - develop
      - rel-*
      - release-*
      - db-*
      - github-actions-*
    tags:
      - db-v*
    paths:
      - package/db/**
      - .github/workflows/build-db.yml
  pull_request:
    branches:
      # - develop
      - rel-*
      - release-*
    paths:
      - package/db/**
      - .github/workflows/build-db.yml

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Set environment
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          if [[ $RELEASE_TAG =~ ^refs\/tags\/db-v.*-rc\..*$ ]]; then
             echo "RELEASE_VERSION=$(echo "${{ github.ref }}" | sed "s/^refs\/tags\/db-v//")" >> $GITHUB_ENV
          fi
      - name: Build wheel (macOS)
        run: |
          cd package/db
          python setup.py bdist_wheel --plat-name mac
      - name: Build wheel (Windows)
        run: |
          cd package/db
          python setup.py bdist_wheel --plat-name win
      - name: Build wheel (Linux)
        uses: ./.github/actions/manylinux
        with:
          pkg: db
          pkg_path: package/db
      - name: Build wheel (Ubuntu 16.04)
        uses: ./.github/actions/manylinux
        with:
          pkg: db
          pkg_path: package/db
          linux_dist: ubuntu1604
      - name: Build wheel (Debian 9)
        uses: ./.github/actions/manylinux
        with:
          pkg: db
          pkg_path: package/db
          linux_dist: debian9
      - name: Upload wheel (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-linux
          path: package/db/dist/fiftyone_db-*linux*.whl
      - name: Upload wheel (Ubuntu 16.04)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-ubuntu1604
          path: package/db/dist/*ubuntu1604*.whl
      - name: Upload wheel (Debian 9)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-debian9
          path: package/db/dist/*debian9*.whl
      - name: Upload wheel (macOS)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-macos
          path: package/db/dist/*macos*.whl
      - name: Upload wheel (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-windows
          path: package/db/dist/*win*.whl

  test:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
      - name: Download fiftyone-db wheel
        uses: actions/download-artifact@v2
        with:
          name: wheel-linux
          path: downloads
      - name: Install fiftyone-db
        run: |
          pip3 install downloads/*.whl
      - name: Install test dependencies
        run: |
          pip3 install pytest
      - name: Run tests
        run: |
          cd package/db/
          python3 -m pytest --verbose tests/

  publish:
    runs-on: ubuntu-18.04
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/db-v')
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          path: downloads
      - name: Install dependencies
        run: |
          pip3 install twine
      - name: Set environment
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          if [[ $RELEASE_TAG =~ ^refs\/tags\/db-v.*-rc\..*$ ]]; then
             echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_TEST_PYPI_TOKEN }}" >> $GITHUB_ENV
             echo "TWINE_REPOSITORY=testpypi" >> $GITHUB_ENV
          else
             echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_PYPI_TOKEN }}" >> $GITHUB_ENV
             echo "TWINE_REPOSITORY=pypi" >> $GITHUB_ENV
          fi
      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_NON_INTERACTIVE: 1
        run: |
          twine upload downloads/wheel-*/*.whl
