name: Build docs

on:
  push:
    branches:
      # - develop
      - rel-*
      - release-*
      - docs-*
      - github-actions-*
    tags:
      - v*
      - docs-publish
    paths:
      - .github/workflows/build-docs.yml
      - docs/**
      - examples/**
      - fiftyone/**
      - "**.py"
      - "**.md"
      - "**.rst"
  pull_request:
    branches:
      - develop
      - rel-*
      - release-*
    paths:
      - .github/workflows/build-docs.yml
      - docs/**
      - examples/**
      - fiftyone/**
      - "**.py"
      - "**.md"
      - "**.rst"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      FIFTYONE_DO_NOT_TRACK: true
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Install fiftyone-db
        working-directory: package/db
        run: |
          python setup.py bdist_wheel
          pip install dist/*.whl
      - name: Install ETA from source
        run: |
          git clone https://github.com/voxel51/eta eta --depth 1 --branch develop
          cd eta
          python setup.py bdist_wheel
          pip install ./dist/*.whl
      - name: Install
        run: |
          sudo apt-get install pandoc
          pip install scikit-learn scikit-image
          pip install --use-deprecated=legacy-resolver -r requirements/docs.txt
          pip install --pre --extra-index-url https://test.pypi.org/simple/ fiftyone-brain
          pip install pycocotools tensorflow torch torchvision
          pip install -e .
      - name: Set environment
        env:
          REF: ${{ github.ref }}
        run: |
          if [[ $RELEASE_TAG =~ ^refs\/tags\/.*$ ]]; then
             echo "FO_DOCS_VERSION_REF=$(echo "${{ github.ref }}" | sed "s/^refs\/tags\/v/")" >> $GITHUB_ENV
          elif [[ $REF =~ ^refs\/head\/.*$ ]]; then
             echo "FO_DOCS_VERSION_REF=$(echo "${{ github.ref }}" | sed "s/^refs\/head\//")" >> $GITHUB_ENV
          fi
      - name: Build docs
        run: |
          ./docs/generate_docs.bash
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/build/html/

  publish:
    needs: [build]
    if: (startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'rc')) || github.ref == 'refs/tags/docs-publish'
    runs-on: ubuntu-18.04
    steps:
      - name: Clone website
        uses: actions/checkout@v2
        with:
          repository: voxel51/website
          token: ${{ secrets.FIFTYONE_GITHUB_TOKEN }}
          ref: develop
      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs-download/
      - name: Update docs
        run: |
          find docs-download/
          test -f docs-download/genindex.html
          rm -r source/docs/fiftyone/
          cp -r docs-download/ source/docs/fiftyone/
          rm -r docs-download/
      - name: Create website PR
        uses: peter-evans/create-pull-request@v2
        with:
          branch: fiftyone-docs
          commit-message: |
            Update fiftyone docs (${{ github.ref }})

            voxel51/fiftyone@${{ github.sha }}
          title: Automated fiftyone documentation update
          body: " "
          token: ${{ secrets.FIFTYONE_GITHUB_TOKEN }}
          author: voxel51-bot <bot@voxel51.com>
          labels: documentation
          reviewers: brimoor, benjaminpkane
          team-reviewers: developers
