name: Build and Publish Dev Docker Image

on:
  workflow_call:
    inputs:
      fiftyone-version:
        required: true
        type: string
      publish:
        required: true
        type: string
      teams-app-version:
        required: true
        type: string
    secrets:
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GOOGLE_SERVICE_ACCOUNT:
        required: true

jobs:
  build-and-publish-dev-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - id: docker-auth
        if: inputs.publish == 'internal'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Voxel51 Internal Registry
        if: inputs.publish == 'internal'
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.docker-auth.outputs.access_token }}

      - name: Build Docker Image and Publish Internally
        if: inputs.publish == 'internal'
        uses: docker/build-push-action@v3
        with:
          context: deployment/docker
          build-args: |
            FIFTYONE_VERSION=${{ inputs.fiftyone-version }}
            GAR_TOKEN=${{ steps.docker-auth.outputs.access_token }}
            TEAMS_APP_VERSION=${{ inputs.teams-app-version }}
            TEAMS_DESKTOP_VERSION=${{ inputs.teams-desktop-version }}
          push: true
          tags: |
            us-central1-docker.pkg.dev/computer-vision-team/dev-docker/fiftyone-teams-app:v${{ inputs.teams-app-version }}
            us-central1-docker.pkg.dev/computer-vision-team/dev-docker/fiftyone-teams-app:latest
