name: Bump Version

on:
  push:
    tags:
      - bump-*

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  get-bump-parts:
    runs-on: ubuntu-20.04
    outputs:
      bump-level: ${{ steps.bump-parts.outputs.group2 }}
      bump-match: ${{ steps.bump-parts.outputs.match }}
      bump-package: ${{ steps.bump-parts.outputs.group1 }}
    steps:
      - name: Clone fiftyone-teams
        uses: actions/checkout@v3

      - name: Get Bump Part
        id: bump-parts
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs\/tags\/bump-(fiftyone|teams-app|all)-(major|minor|patch|dev)$'

      - name: Check for Bump Part Error
        if: steps.bump-parts.outputs.match == ''
        run: |
          echo "bump tag must be of the format bump-(fiftyone|teams-app|all)-(major|minor|patch|dev)"
          echo "${{ github.ref }} does not match that pattern (but obviously starts with 'bump')"
          echo "please try again or check the workflow to add additional options"

  bump-version:
    runs-on: ubuntu-20.04
    needs: get-bump-parts
    if: needs.get-bump-parts.outputs.bump-match != ''
    env:
      NEWVERSION: 1.8.3.dev0+voxel51
      BUMP_LEVEL: ${{ needs.get-bump-parts.outputs.bump-level }}
    outputs:
      fiftyone-version: ${{ steps.get-bumped-versions.outputs.fiftyone-version }}
      teams-app-version: ${{ steps.get-bumped-versions.outputs.teams-app-version }}
    steps:
      - name: Clone fiftyone-teams
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install voxel51 newversion
        run: |
          pip install --extra-index-url https://oauth2accesstoken:${{ steps.auth.outputs.access_token }}@${{ secrets.GAR_PYTHON_REPO }}/simple newversion==$NEWVERSION

      - name: Bump FiftyOne Version
        if: needs.get-bump-parts.outputs.bump-package == 'fiftyone'
        run: newversion package | newversion bump $BUMP_LEVEL | newversion set_package

      - name: Bump Teams App Version
        if: needs.get-bump-parts.outputs.bump-package == 'teams-app'
        working-directory: package/teams
        run: newversion package | newversion bump $BUMP_LEVEL | newversion set_package

      - name: Bump All Package Versions
        if: needs.get-bump-parts.outputs.bump-package == 'all'
        run: |
          newversion package | newversion bump $BUMP_LEVEL | newversion set_package
          cd package/teams
          newversion package | newversion bump $BUMP_LEVEL | newversion set_package

      - name: Get Bumped Versions
        id: get-bumped-versions
        run: |
          echo "::set-output name=fiftyone-version::$(newversion package)"
          cd package/teams
          echo "::set-output name=teams-app-version::$(newversion package)"

      - name: Commit Bumps and Push Tags
        env:
          FIFTYONE_VERSION: ${{ steps.get-bumped-versions.outputs.fiftyone-version }}
          TEAMS_APP_VERSION: ${{ steps.get-bumped-versions.outputs.teams-app-version }}
        run: |
          git add setup.py package/teams/setup.py
          git commit -m "automated ${BUMP_LEVEL} version bump to teams-v${FIFTYONE_VERSION} and teams-app-v${TEAMS_APP_VERSION}"
          git push --follow-tags origin HEAD:$(git branch -r --contains ${{ github.ref }})
