name: Daily dev.fiftyone.ai Deploy
on:
  workflow_dispatch:
    inputs:
      deployer-branch:
        default: 'main'
        description: 'Which cloud-build-and-deploy branch to use'
        type: string
  schedule:
    # jobs run at UTC time, this should be 7:22 AM EST, every day Mon-Sat
    - cron: 22 11 * * 1-6

jobs:
  call-dev-cloud-build-and-deploy:
    uses: voxel51/cloud-build-and-deploy/.github/workflows/dev-build-and-deploy.yml@main
    with:
      deployer-branch: ${{ inputs.deployer-branch || 'main' }}
    secrets:
      ORG_GOOGLE_WORKLOAD_IDP: ${{ secrets.ORG_GOOGLE_WORKLOAD_IDP }}
