name: Deploy Voxel51 Environment

on:
  workflow_call:
    inputs:
      domain-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      fiftyone-version:
        required: true
        type: string
      teams-app-version:
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
      SSH_KEY:
        required: true
      SSH_USER:
        required: true
      UPPTIME_PAT:
        required: true

jobs:
  deploy-environment:
    runs-on: ubuntu-20.04
    steps:
      - id: current-timestamp
        name: get current timestamp
        run: echo "::set-output name=iso8601::$(date -Iseconds)"

      - id: future-timestamp
        name: get future timestamp
        run: echo "::set-output name=iso8601::$(date -Iseconds -d '+15 minutes')"

      - name: create upptime maintenance issue
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.UPPTIME_PAT }}
          owner: voxel51
          repo: upptime
          title: Bumping ${{ inputs.domain-name }} fiftyone-teams-app to ${{ inputs.teams-app-version }}
          body: |
            Bumping ${{ inputs.domain-name }} to:
              fiftyone-teams version ${{ inputs.fiftyone-version }}
              fiftyone-teams-app version ${{ inputs.teams-app-version }}
            <!--
            start: ${{ steps.current-timestamp.outputs.iso8601 }}
            end: ${{ steps.future-timestamp.outputs.iso8601 }}
            expectedDown: ${{ inputs.domain-name }}
            -->
          labels: maintenance

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_SSH_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host updateme
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
            SendEnv APP_VERSION
          END
        env:
          PRIVATE_SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Update voxel51.dev.fiftyone.ai
        run: |
          ssh updateme '/teams/deploy/${{ inputs.environment }}/deploy.sh'
        env:
          APP_VERSION: v${{ inputs.teams-app-version }}
