name: Test e2e

on: workflow_call

jobs:
  test-e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      FIFTYONE_DO_NOT_TRACK: true
      ELECTRON_EXTRA_LAUNCH_ARGS: "--disable-gpu"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          node-version: 16

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        id: pip-cache
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: |
            requirements/common.txt
            requirements/github.txt
            requirements/test.txt

      - name: Install requirements
        if: steps.pip-cache.outputs.cache-hit != true
        run: |
          pip install -r requirements/github.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: |
            app/node_modules
            app/.yarn/cache
          key: node-modules-${{ hashFiles('app/yarn.lock') }}

      - name: Install app
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: cd app && yarn install

      - name: Build app
        run: make app

      - name: Install fiftyone
        run: pip install .

      - name: Configure
        id: test_config
        run: |
          python tests/utils/setup_config.py
          python tests/utils/github_actions_flags.py

      - name: FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install E2E dependencies
        run: yarn
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
        working-directory: ./e2e

      - name: Run Playwright tests
        run: yarn e2e
        working-directory: ./e2e

      - name: Upload snapshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
