name: Publish

on:
  push:
    tags:
      - teams-v[0-9]+.[0-9]+.[0-9]+
      - teams-v[0-9]+.[0-9]+.[0-9]+rc[0-9]+

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/teams-v')
    needs: [build, test]
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{github.run_id}}
          name: dist
          path: dist
      - name: Install dependencies
        run: |
          pip3 install twine
      - name: Set environment
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_TEAMS_PYPI_PASSWORD }}" >> $GITHUB_ENV
          echo "TWINE_REPOSITORY=pypi" >> $GITHUB_ENV
      - name: Upload to pypi
        env:
          TWINE_USERNAME: teams-ci
          TWINE_NON_INTERACTIVE: 1
        run: |
          python3 -m twine upload --repository-url https://pypi.fiftyone.ai dist/*

  build-image:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: docker
        run: make docker-export -o python
      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: fiftyone.tar.gz
