name: teams-app-e2e

on: workflow_call

jobs:
  teams-app-e2e:
    timeout-minutes: 90
    runs-on: ubuntu-latest-m
    env:
      BASE_URL: https://newauth.dev.fiftyone.ai
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache E2E Node Modules
        id: e2e-node-cache
        uses: actions/cache@v4
        with:
          path: |
            teams-app/e2e-pw/node_modules
          key: node-modules-${{ hashFiles('teams-app/e2e-pw/yarn.lock') }}

      - name: Install E2E dependencies if not cached
        run: yarn install
        if: steps.e2e-node-cache.outputs.cache-hit != 'true'
        working-directory: teams-app/e2e-pw

      - name: Get Playwright version
        id: playwright-version
        run: |
          echo "PLAYWRIGHT_VERSION=$(node -e "process.stdout.write(require('@playwright/test/package.json').version)")" >> $GITHUB_OUTPUT
        working-directory: teams-app/e2e-pw

      - name: Install Playwright dependencies
        run: |
          if ! npx playwright install-deps --check; then
            npx playwright install-deps
          else
            echo "Playwright dependencies are already installed."
          fi

      - name: Cache playwright browser
        uses: actions/cache@v4
        id: playwright-browser-cache
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
          working-directory: teams-app/e2e-pw

      - name: Install Playwright browser if not cached
        run: yarn playwright install
        if: steps.playwright-browser-cache.outputs.cache-hit != 'true'
        working-directory: teams-app/e2e-pw

      - name: Run Playwright tests
        run: yarn e2e
        working-directory: teams-app/e2e-pw
        env:
          BASE_URL: ${{ env.BASE_URL }}
          KC_ADMIN_USERNAME: ${{ secrets.KC_ADMIN_USERNAME }}
          KC_ADMIN_PASSWORD: ${{ secrets.KC_ADMIN_PASSWORD }}
          KC_GUEST_PASSWORD: ${{ secrets.KC_GUEST_PASSWORD }}
          KC_GUEST_EMAIL: ${{ secrets.KC_GUEST_EMAIL }}
          KC_GUEST_USERNAME: ${{ secrets.KC_GUEST_USERNAME }}
          SUPERADMIN_SECRET: ${{ secrets.CAS_SUPERADMIN_SECRET }}
          PLAYWRIGHT_BROWSERS_PATH: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Lint Playwright tests
        run: yarn lint
        working-directory: teams-app/e2e-pw

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: teams-app/e2e-pw/playwright-report/
          retention-days: 30
